# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-17 23:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('anuncios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='favorites_user', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('anuncios', models.ManyToManyField(related_name='favorites_anuncios', to='anuncios.Anuncio', verbose_name='Anuncio')),
            ],
        ),
    ]
