# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-17 23:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIpn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=127, verbose_name='Tipo pago value')),
                ('item_number', models.CharField(max_length=127, verbose_name='Tipo pago clave')),
                ('invoice', models.CharField(max_length=127, unique=True, verbose_name='ID Factura')),
                ('txn_id', models.CharField(max_length=255)),
                ('payment_status', models.CharField(max_length=10)),
                ('total_amount', models.FloatField(default=0.0, verbose_name='Cantidad pagada')),
                ('receiver_amount', models.FloatField(default=0.0, verbose_name='Cantidad recibida')),
                ('post_data', models.TextField(verbose_name='Datos retornados por PayPal')),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_ipn_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
