# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-03-24 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_auto_20170323_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerthabitacion',
            name='genero',
            field=models.CharField(blank=True, choices=[('INDIFERENTE', 'Indiferente'), ('CHICO', 'Chicos'), ('CHICA', 'Chicas')], default='INDIFERENTE', max_length=20, verbose_name='Genero'),
        ),
    ]
