# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-03-24 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_alerthabitacion_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerthabitacion',
            name='genero',
            field=models.CharField(choices=[('INDIFERENTE', 'Indiferente'), ('CHICO', 'Chicos'), ('CHICA', 'Chicas')], default='INDIFERENTE', max_length=20, verbose_name='Genero'),
        ),
    ]
