# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-17 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anuncios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAnuncio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='anuncios/', verbose_name='Imagen')),
                ('thumbnail', models.CharField(blank=True, max_length=100, verbose_name='Thumbnail')),
                ('description', models.CharField(blank=True, default='', max_length=100, verbose_name='Descripción')),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_anuncio', to='anuncios.Anuncio', verbose_name='Anuncio')),
            ],
        ),
    ]
