# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-17 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Asunto')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('username', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('screenshot', models.ImageField(blank=True, default='', upload_to='contact/screenshots', verbose_name='Imagen')),
                ('read', models.BooleanField(default=False, verbose_name='Leído')),
                ('is_register', models.BooleanField(verbose_name='Usuario registrado')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
            ],
            options={
                'verbose_name_plural': 'Mensajes contacto',
                'verbose_name': 'Mensaje contacto',
                'ordering': ('read', '-create_at'),
                'permissions': (('can_view_messages', 'Puede ver mensaje contacto'),),
            },
        ),
    ]
