# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-17 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='Se auto genera', max_length=12)),
                ('payment_promo', models.CharField(choices=[('PREMIUM1', '1 Mes Premium'), ('PREMIUM3', '3 Meses Premium'), ('PREMIUM6', '6 Meses Premium'), ('PREMIUM12', '1 Año Premium'), ('ANUNCIO', 'Anuncio Premium')], max_length=20)),
                ('active', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('expire_at', models.DateTimeField(blank=True, help_text='Por defecto 90 días', verbose_name='Fecha expiración')),
            ],
        ),
    ]
