# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='expire_at',
            field=models.DateTimeField(blank=True, help_text='Por defecto 30 días', verbose_name='Fecha expiración'),
        ),
    ]
