# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-17 23:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, help_text='Si se quiere auto-generar otro slug, dejarlo en blanco.', max_length=255, unique=True)),
                ('image_header', models.ImageField(blank=True, null=True, upload_to='articles/headers', verbose_name='imagen cabecera')),
                ('body', models.TextField(verbose_name='cuerpo')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('views', models.IntegerField(default=0, verbose_name='vistas')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha creación')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='fecha modificación')),
            ],
            options={
                'verbose_name_plural': 'artículos',
                'verbose_name': 'articulo',
                'ordering': ('-create_at',),
            },
        ),
        migrations.CreateModel(
            name='ArticleSubscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('token_unsigned', models.CharField(max_length=30, unique=True, verbose_name='token unregister')),
            ],
            options={
                'verbose_name_plural': 'suscritos a artículos',
                'verbose_name': 'suscrito a artículos',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, help_text='Si se quiere auto-generar otro slug, dejarlo en blanco.', max_length=255, unique=True)),
                ('views', models.IntegerField(default=0, verbose_name='vistas')),
                ('thumbnail', models.ImageField(upload_to='articles/tags', verbose_name='miniatura')),
            ],
            options={
                'verbose_name_plural': 'etiquetas',
                'verbose_name': 'etiqueta',
                'ordering': ('-views',),
            },
        ),
        migrations.AddField(
            model_name='article',
            name='default_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_default_tag', to='blog.Tag', verbose_name='etiqueta principal'),
        ),
        migrations.AddField(
            model_name='article',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_owner', to=settings.AUTH_USER_MODEL, verbose_name='autor'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(related_name='article_tags', to='blog.Tag', verbose_name='etiquetas'),
        ),
    ]
