# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170607_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Descripción'),
        ),
    ]
