# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-17 23:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anuncios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(verbose_name='Puntuación')),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratio_anuncio', to='anuncios.Anuncio', verbose_name='anuncios')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratio_user', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name_plural': 'Ratios',
                'verbose_name': 'Ratio',
            },
        ),
        migrations.AlterUniqueTogether(
            name='ratio',
            unique_together=set([('user', 'anuncio')]),
        ),
    ]
